name: ci-nodejs
on: [push]
jobs:
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 20.6.1
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test